apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskbloom-backend
  labels:
    app: taskbloom-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: taskbloom-backend
  template:
    metadata:
      labels:
        app: taskbloom-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}:{{ .Values.backend.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}