apiVersion: v1
kind: Service
metadata:
  name: taskbloom-backend
spec:
  type: NodePort
  selector:
    app: taskbloom-backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      nodePort: {{ .Values.backend.nodePort }}